acme_article_homepage:
    path:     article/hello/{name}
    defaults: { _controller: AcmePortalBundle:Default:index }
    
acme_article_new:
    path:     article/new/
    defaults: { _controller: AcmePortalBundle:Article:new }
    
acme_article_show:
    path:     article/show/
    defaults: { _controller: AcmePortalBundle:Article:show }
    
acme_article_index:
    path:     article/index/
    defaults: { _controller: AcmePortalBundle:Article:index }
    
acme_article_form:
    path:     article/form/
    defaults: { _controller: AcmePortalBundle:Article:form }


acme_tag_new:
  path: tag/new/
  defaults:
    _controller: tag_controller:newAction
    
#acme_tag_new:
#    path:     tag/new/
#    defaults: { _controller: AcmePortalBundle:Tag:new }
    
acme_tag_show:
    path:     tag/show/
    defaults: { _controller: AcmePortalBundle:Tag:show }
