# ----------- Tag
acme_tag_new:
  path: tag/new/
  defaults:
    _controller: AcmePortalBundle:Tag:new
    
acme_tag_show:
  path: tag/show/
  defaults:
    _controller: AcmePortalBundle:Tag:show
    
acme_tag_edit:
  path: tag/edit/
  defaults:
    _controller: AcmePortalBundle:Tag:edit
    
acme_tag_delete:
  path: tag/delete/{id}
  defaults:
    _controller: AcmePortalBundle:Tag:delete
    methods:  [DELETE]
    
#acme_tag_new:
#    path:     tag/new/
#    defaults: { _controller: AcmePortalBundle:Tag:new }
    
#acme_tag_show:
#    path:     tag/show/
#    defaults: { _controller: AcmePortalBundle:Tag:show }

# ----------- Article
acme_article_new:
  path: article/new/
  defaults:
    _controller: AcmePortalBundle:Article:new
    
acme_article_show:
  path: article/show/
  defaults:
    _controller: AcmePortalBundle:Article:show
    
acme_article_edit:
  path: article/edit/
  defaults:
    _controller: AcmePortalBundle:Article:edit
    methods:  [UPDATE]
    
acme_article_delete:
  path: article/delete/{id}
  defaults:
    _controller: AcmePortalBundle:Article:delete
    methods:  [DELETE]
    
# ----------- Client
acme_client_new:
  path: client/new/
  defaults:
    _controller: AcmePortalBundle:Client:new
    
acme_client_show:
  path: client/show/
  defaults:
    _controller: AcmePortalBundle:Client:show
    
acme_client_edit:
  path: client/edit/
  defaults:
    _controller: AcmePortalBundle:Client:edit
    methods:  [UPDATE]
    
acme_client_delete:
  path: client/delete/{id}
  defaults:
    _controller: AcmePortalBundle:Client:delete
    methods:  [DELETE]
    
# ----------- Portal
acme_portal_show:
  path: portal/show/
  defaults:
    _controller: AcmePortalBundle:Portal:show
  
acme_portal_visit:
  path: portal/visit/{client}/{article}
  defaults:
    _controller: AcmePortalBundle:Portal:visit
    
acme_portal_overview:
  path: portal/overview/
  defaults:
    _controller: AcmePortalBundle:Portal:overview
