services:
#    acme_portal.example:
#        class: Acme\PortalBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

  tag_controller:
    class: Acme\PortalBundle\Controller\TagController
    calls:
      - [ setContainer, [ "@service_container" ]]
      - [ setFacade, [ "@doctrine" ]]
      
  article_controller:
      class: Acme\PortalBundle\Controller\ArticleController
      calls:
        - [ setContainer, [ "@service_container" ]]
        - [ setFacade, [ "@doctrine" ]]

  acme.portal.listener.before_controller:
    class: Acme\PortalBundle\EventListener\BeforeControllerListener
    tags:
        - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
    arguments: ['@doctrine']
