#acme_task:
#    resource: "@AcmeTaskBundle/Resources/config/routing.yml"
#    prefix:   /

#acme_store:
#    resource: "@AcmeStoreBundle/Resources/config/routing.yml"
#    prefix:   /

acme_portal:
    resource: "@AcmePortalBundle/Resources/config/routing.yml"
    prefix:   /
    
think_mind:
    resource: "@ThinkMindBundle/Resources/config/routing.yml"
    prefix: think
    
#admin:
#    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
#    prefix: /admin
#
#
#_sonata_admin:
#    resource: .
#    type: sonata_admin
#    prefix: /admin

