<?php

namespace Acme\PortalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{
  public function findAllOrderedByDescription()
  {
    return $this->getEntityManager()
      ->createQuery(
        'SELECT t FROM AcmePortalBundle:Client t ORDER BY t.pos, t.name ASC'
      )
      ->getResult();
  }
}
